# The ndarray
The ndarray type is a multidimensional array that is efficient for operations on the whole

## Cheat Sheets
## Overview
Let us create a two dimensional array as followx

In [3]:
import numpy as np
a = np.array([[1,2,3,4,5], [6,7,8,8,10],[11,12,13,14,14]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  8, 10],
       [11, 12, 13, 14, 14]])

We can visualize this array as per the following diagram
  <img alt="" src="./images/ndarray.png">
  
    The number of dimensions is 2 and we can check this using the **ndim** property
#### Dimensions - ndim property

In [8]:
a.ndim

2

#### Shape
The shape give the dimension of each axis. In this example the size of the first axis, axis 0, is 3 elemements and the size of the second axis, axis 1, is 5 elements

In [9]:
a.shape

(3, 5)

#### Indexing
The following access the cell at position 0 on axis0 and position 2 on axis1

In [12]:
a[0,2]

3

whereas the following accesses the cell at position 2 on axis0 and position 0 on axis

In [13]:
a[2,0]

11

## Details
### Creation
#### From sequence 
We can create an ndarray from a sequence like object. The following creates an array with shape (3,5)

In [15]:
a = np.array([[1,2,3,4,5], [6,7,8,8,10],[11,12,13,14,14]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  8, 10],
       [11, 12, 13, 14, 14]])

#### All Zeros/Ones
We can use the zeros/ones functions which takes either a given length for a one dimensional array or a shape for multidimensional array to create arrays of all zeros or all ones.

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### All given value

In [24]:
np.full((3,2),6)

array([[6, 6],
       [6, 6],
       [6, 6]])

#### Identity Matrix

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Arange
The *arange* method is the ndarray equivalent of the range method in standard Python

In [21]:
np.arange(3)

array([0, 1, 2])

### Arithmetic on equal size arrays
Apply the operators on individual elements

In [29]:
a = np.array([[1,2,3], [4,5,6]]); b = 2*a + 2; b

array([[ 4,  6,  8],
       [10, 12, 14]])

In [34]:
fractions = 1.0 / np.arange(1,5); fractions

array([1.        , 0.5       , 0.33333333, 0.25      ])

### Indexing and Slicing
Slicing an ndarray is difference from slicing a list in that the slice is a view on the ndarry. Chaning the slice, changes the source. The following code uses slice to set values into a one dimensional array

In [37]:
a = np.arange(5); a[2:4] = 10; a

array([ 0,  1, 10, 10,  4])

#### The bare slice
We can use the bare slice [:] to asign values to a whole slice

In [41]:
a = np.arange(5); a[:] = 99; a

array([99, 99, 99, 99, 99])

#### Multidimensional slcing
The following diagram shows the effects of 2 dimensional slicing

  <img alt="" src="./images/slicing.png">

In [50]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,14]])
a[:2,:2]

array([[1, 2],
       [6, 7]])